std = "lua51"
max_line_length = 160

-- World of Warcraft API globals used by the addon.
read_globals = {
    "AcceptQuest",
    "AchievementFrame",
    "AchievementFrame_LoadUI",
    "AchievementFrame_SelectAchievement",
    "AchievementFrame_ToggleAchievementFrame",
    "C_Container",
    "C_CreatureInfo",
    "C_GossipInfo",
    "C_Item",
    "C_Map",
    "C_NamePlate",
    "C_QuestLog",
    "C_Timer",
    "ClearOverrideBindings",
    "CompleteQuest",
    "CLOSE",
    "CreateFrame",
    "DEFAULT_CHAT_FRAME",
    "DeleteMacro",
    "GameTooltip",
    "GameFontHighlightSmall",
    "GetAchievementCriteriaInfo",
    "GetAchievementInfo",
    "GetAchievementNumCriteria",
    "GetBindingKey",
    "GetCursorPosition",
    "GetCVarBool",
    "GetMacroInfo",
    "GetNumMacros",
    "GetNumQuestChoices",
    "GetQuestID",
    "GetQuestReward",
    "GetTime",
    "InCombatLockdown",
    "issecretvalue",
    "IsControlKeyDown",
    "IsQuestCompletable",
    "KEY_BINDINGS",
    "MAX_ACCOUNT_MACROS",
    "Minimap",
    "NUM_BAG_SLOTS",
    "Enum",
    "GossipFrame",
    "GossipFrameTitleText",
    "OpenAchievementFrameToAchievement",
    "REAGENTBAG_CONTAINER",
    "SetOverrideBinding",
    "SetOverrideBindingClick",
    "Settings",
    "SettingsPanel",
    "UIParent",
    "UnitExists",
    "UnitGUID",
    "UnitIsVisible",
    "UnitName",
}

-- Globals intentionally provided by the addon or its Bindings.xml file.
globals = {
    "BINDING_HEADER_MIXINGMYSTERIESHELPER",
    "BINDING_NAME_MIXINGMYSTERIESHELPER_ADVANCE",
    "MixingMysteriesHelperBinding",
    "MixingMysteriesHelperDB",
    "SLASH_MIXINGMYSTERIESHELPER1",
    "SLASH_MIXINGMYSTERIESHELPER2",
    "SlashCmdList",
}

ignore = {
    "212/self",
    "212/event",
    "212/unit",
}
